--Query to use the payroll_service Database
use payroll_service

--Query to insert some data in the employee_payroll table
Insert into employee_payroll (name, salary, start_date) values ('A', 30000, '2022-11-15')
Insert into employee_payroll (name, salary, start_date) values ('B', 40000, '2022-10-15')
Insert into employee_payroll (name, salary, start_date) values ('C', 50000, '2022-09-15')
Insert into employee_payroll (name, salary, start_date) values ('D', 60000, '2022-08-15')
Insert into employee_payroll (name, salary, start_date) values ('E', 70000, '2022-07-15')
Insert into employee_payroll (name, salary, start_date) values ('F', 80000, '2022-06-15')
Insert into employee_payroll (name, salary, start_date) values ('G', 90000, '2022-05-15')
Insert into employee_payroll (name, salary, start_date) values ('H', 95000, '2022-04-15')
Insert into employee_payroll (name, salary, start_date) values ('I', 20000, '2018-01-01')
Insert into employee_payroll (name, salary, start_date) values ('J', 10000, '2017-01-01')